#!/usr/bin/env python3
"""
Script 49c: Regenerate Stage 09 Interactive Networks with Full Node Metadata
=============================================================================

Reconstructs PyVis interactive network visualizations using the master node table
generated by Script 49b, with complete node styling:
  
  - Node borders colored by cell_type (from Script 49)
  - Node labels prefixed with ★ (oncogene) or ▼ (TSG) symbols
  - Rich tooltips with all metadata columns
  - Edge weights and link types preserved from Stage 09 edge files

OUTPUT SCHEMA (in tooltips):
  approved_symbol     Script 47  HGNC canonical symbol
  entrez_id           Script 47  NCBI gene ID
  ncbi_summary        Script 48  Biological description
  cell_type           Script 49  Test-condition cell type
  cell_type_ref       Script 49  Reference-condition cell type (Normal)
  ct_switched         Script 49  Boolean flag for publishable condition switch
  ct_source           Script 49  Annotation source (zscore/cluster/immune)
  is_cosmic           Script 49  COSMIC cancer database flag
  is_oncokb           Script 49  OncoKB flag
  is_disgenet         Script 49  DisGeNET disease association flag

INPUTS:
    - results/23_node_annotation/01_input_data/annotation_bridge/master_node_table.csv (from Script 49b)
  - results/18_differential_viz/{pair}/{branch}/*edges_viz.csv
  - results/19_persistent_overlap/{pair}/*viz.csv
  - results/19_persistent_overlap/{pair}/*viz.csv

OUTPUTS:
  - Updated *_network_interactive.html files with full PyVis visualization
  - Node styling: cell-type borders + cancer gene markers
  - Tooltips: complete metadata with biological context
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Optional
import re

import pandas as pd
import networkx as nx
import numpy as np

try:
    from pyvis.network import Network
    HAS_PYVIS = True
except ImportError:
    HAS_PYVIS = False
    print("⚠️  WARNING: pyvis not installed. Install with: pip install pyvis")

REPO_ROOT = Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Regenerate Stage 09 interactive networks with full node metadata"
    )
    p.add_argument(
        "--master-table",
        default="results/23_node_annotation/01_input_data/annotation_bridge/master_node_table.csv",
        help="Master node table with cell-type + cancer gene data"
    )
    p.add_argument(
        "--network-viz-dirs",
        nargs="+",
        default=[
            "results/18_differential_viz",
            "results/19_persistent_overlap",
            "results/19_persistent_overlap",
        ],
        help="Visualization directories containing edge files"
    )
    p.add_argument(
        "--physics",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Enable PyVis physics simulation"
    )
    p.add_argument(
        "--iterations",
        type=int,
        default=500,
        help="Physics iterations for network layout"
    )
    p.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility"
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't write files, just report what would be done"
    )
    return p.parse_args()


def get_cell_type_color(cell_type: str | float) -> str:
    """
    Map cell_type to hex color for node borders.
    
    Returns: Hex color code (e.g., '#FF6B6B')
    """
    if pd.isna(cell_type) or cell_type is None:
        return "#CCCCCC"  # Grey for unknown
    
    color_map = {
        "BCell": "#0072B2",
        "Cycling": "#E74C3C",
        "Epithelial": "#2ECC71",
        "Endo": "#F39C12",
        "Endothelial": "#F39C12",
        "Fibroblast": "#95A5A6",
        "Fibro": "#7F8C8D",
        "Fibro2": "#7F8C8D",
        "Myeloid": "#9B59B6",
        "Macro": "#E67E22",
        "TCell": "#3498DB",
        "TCell2": "#3498DB",
        "T_cell": "#3498DB",
        "Luminal_Epi": "#27AE60",
        "Luminal": "#27AE60",
        "Basal_Epi": "#16A085",
        "Basal": "#16A085",
        "Plasma": "#E74C3C",
        "NK": "#F1C40F",
        "Unknown": "#CCCCCC",
    }
    
    if cell_type in color_map:
        return color_map[cell_type]
    
    # Case-insensitive match
    for key, color in color_map.items():
        if key.lower() == str(cell_type).lower():
            return color
    
    # Hash-based fallback
    h = hash(str(cell_type)) % 0xFFFFFF
    return f"#{h:06X}"


def build_node_label(row: pd.Series) -> str:
    """
    Build node label with cancer gene prefixes.
    
    Returns: "★ BRCA1" for oncogene, "▼ TP53" for TSG, "ACTB" for normal
    """
    symbol = str(row.get("approved_symbol", ""))
    
    prefix = ""
    if pd.notna(row.get("oncokb_is_oncogene")) and row["oncokb_is_oncogene"]:
        prefix += "★"
    if pd.notna(row.get("oncokb_is_tsg")) and row["oncokb_is_tsg"]:
        prefix += "▼"
    
    return f"{prefix} {symbol}".strip()


def build_tooltip(row: pd.Series) -> str:
    """
    Build rich tooltip with all node metadata.
    
    Format: plain text with newlines (HTML escaping handled by PyVis)
    """
    lines = []
    
    # Gene identifier
    symbol = row.get("approved_symbol", "?")
    entrez = row.get("entrez_id_x") or row.get("entrez_id", "?")
    lines.append(f"Gene: {symbol}")
    if pd.notna(entrez) and entrez != "?":
        lines.append(f"Entrez: {int(entrez) if isinstance(entrez, float) else entrez}")
    
    # Cell type info
    ct = row.get("cell_type")
    ct_ref = row.get("cell_type_ref")
    ct_src = row.get("ct_source", "")
    
    if pd.notna(ct):
        lines.append(f"Cell Type: {ct}")
        if pd.notna(ct_ref) and ct != ct_ref:
            lines.append(f"  (Ref: {ct_ref}) ⚡ SWITCHED")
        lines.append(f"  Source: {ct_src}")
    else:
        lines.append("Cell Type: [not annotated]")
    
    # Cancer gene status
    is_oncogene = row.get("oncokb_is_oncogene")
    is_tsg = row.get("oncokb_is_tsg")
    
    cancer_flags = []
    if pd.notna(is_oncogene) and is_oncogene:
        cancer_flags.append("Oncogene")
    if pd.notna(is_tsg) and is_tsg:
        cancer_flags.append("Tumor Suppressor")
    if cancer_flags:
        lines.append(f"Cancer Gene: {', '.join(cancer_flags)}")
    
    # Disease association flags
    is_cosmic = row.get("is_cosmic")
    is_oncokb = row.get("is_oncokb")
    is_disgenet = row.get("is_disgenet")
    
    flags = []
    if pd.notna(is_cosmic) and is_cosmic:
        flags.append("COSMIC")
    if pd.notna(is_oncokb) and is_oncokb:
        flags.append("OncoKB")
    if pd.notna(is_disgenet) and is_disgenet:
        flags.append("DisGeNET")
    if flags:
        lines.append(f"Databases: {', '.join(flags)}")
    
    # Gene summary (if available, truncated)
    summary = row.get("ncbi_summary")
    if pd.notna(summary) and summary and len(str(summary)) > 0:
        summary_str = str(summary)[:150]
        if len(str(summary)) > 150:
            summary_str += "..."
        lines.append(f"Summary: {summary_str}")
    
    # Aliases
    aliases = row.get("alias_symbols")
    if pd.notna(aliases) and aliases and str(aliases).strip():
        alias_list = str(aliases).split("|")[:5]  # Show max 5
        lines.append(f"Aliases: {', '.join(alias_list)}")
    
    return "\n".join(lines)


def load_edge_file(edge_file: Path) -> pd.DataFrame:
    """
    Load edge file for network reconstruction.
    
    Expected columns: gene_a, gene_b, weight, [optional: link_type, persist_score, etc.]
    """
    try:
        df = pd.read_csv(edge_file)
        required_cols = ["gene_a", "gene_b"]
        if not all(col in df.columns for col in required_cols):
            print(f"⚠️  SKIP: Missing required columns in {edge_file.name}")
            return pd.DataFrame()
        return df
    except Exception as e:
        print(f"⚠️  ERROR reading {edge_file.name}: {e}")
        return pd.DataFrame()


def find_edge_files(viz_dir: Path, pair_name: str) -> list[Path]:
    """
    Find edge files for a given pair in a visualization directory.
    
    Returns: List of edge file paths
    """
    pair_dir = viz_dir / pair_name
    if not pair_dir.exists():
        return []
    
    # Look for *edges*.csv or *_viz.csv files
    edge_files = list(pair_dir.glob("*edges*.csv")) + list(pair_dir.glob("**/*edges*.csv"))
    return sorted(set(edge_files))  # Deduplicate


def regenerate_network_html(
    pair_name: str,
    edge_data: pd.DataFrame,
    master_df: pd.DataFrame,
    output_file: Path,
    physics: bool = True,
    iterations: int = 500,
    seed: int = 42,
    dry_run: bool = False,
) -> bool:
    """
    Regenerate a single interactive network HTML with PyVis.
    
    Args:
      pair_name: Pair identifier (e.g., "ER_tumor__vs__Normal")
      edge_data: DataFrame with gene_a, gene_b, weight columns
      master_df: Master node table to extract node metadata
      output_file: Path to write HTML
      physics: Enable physics simulation
      iterations: Number of physics iterations
      seed: Random seed for reproducibility
      dry_run: If True, don't write files
    
    Returns:
      True if successful, False otherwise
    """
    if edge_data.empty:
        return False
    
    try:
        # Build node list from edges + master table
        genes = set(edge_data["gene_a"]) | set(edge_data["gene_b"])
        
        # Filter master table to this pair
        pair_data = master_df[master_df["pair_name"] == pair_name]
        
        # Create lookup dict
        node_lookup = {}
        for _, row in pair_data.iterrows():
            node_lookup[row["approved_symbol"]] = row
        
        # Create PyVis network
        net = Network(
            height="750px",
            width="100%",
            directed=False,
            physics=physics,
        )
        
        # Set physics options if enabled
        if physics:
            net.toggle_physics(True)
            net.show_buttons(filter_=["physics"])
        
        # Add nodes
        for gene in genes:
            node_row = node_lookup.get(gene)
            
            if node_row is not None:
                cell_type = node_row.get("cell_type")
                border_color = get_cell_type_color(cell_type)
                label = build_node_label(node_row)
                title = build_tooltip(node_row)
            else:
                border_color = "#CCCCCC"
                label = gene
                title = f"Gene: {gene}\n[Master table: not found]"
            
            net.add_node(
                gene,
                label=label,
                title=title,
                color={
                    "border": border_color,
                    "background": "#FFFFFF",
                    "highlight": {"border": border_color, "background": "#F0F0F0"},
                },
                borderWidth=3,
                font={"size": 11},
            )
        
        # Add edges
        for _, edge_row in edge_data.iterrows():
            gene_a = edge_row["gene_a"]
            gene_b = edge_row["gene_b"]
            weight = edge_row.get("weight", 1.0)
            
            # Edge color based on link type if available
            edge_color = "#CCCCCC"
            if "link_type" in edge_row.index:
                link_type_map = {"C": "#2a9d8f", "S": "#f4a261", "D": "#e76f51"}
                edge_color = link_type_map.get(edge_row["link_type"], "#CCCCCC")
            
            # Edge width proportional to weight
            width = min(5.0, max(0.5, float(weight) / 2.0))
            
            net.add_edge(gene_a, gene_b, weight=weight, width=width, color=edge_color)
        
        # Configure layout
        net.toggle_physics(physics)
        if physics:
            # Stabilize with specified iterations
            net.show_buttons(filter_=["physics"])
        
        # Write HTML if not dry-run
        if not dry_run:
            output_file.parent.mkdir(parents=True, exist_ok=True)
            net.show(str(output_file))
            return True
        else:
            return True
        
    except Exception as e:
        print(f"⚠️  ERROR regenerating network for {pair_name}: {e}")
        return False


def main():
    args = parse_args()
    
    if not HAS_PYVIS:
        print("❌ ERROR: pyvis required. Install with: pip install pyvis")
        return
    
    print("=" * 80)
    print("Script 49c: Regenerate Stage 09 Interactive Networks")
    print("=" * 80)
    
    # Load master table
    master_path = Path(REPO_ROOT) / args.master_table
    if not master_path.exists():
        print(f"❌ ERROR: Master table not found: {master_path}")
        print(f"   Run Script 49b first to generate: {master_path}")
        return
    
    print(f"\n📖 Loading master node table: {master_path}")
    master_df = pd.read_csv(master_path)
    print(f"   Loaded {len(master_df)} gene-pair records")
    
    # Collect all pairs
    all_pairs = sorted(master_df["pair_name"].unique())
    print(f"   Pairs: {all_pairs}")
    
    # Process each visualization directory
    regenerated = 0
    skipped = 0
    
    for viz_dir_str in args.network_viz_dirs:
        viz_dir = Path(REPO_ROOT) / viz_dir_str
        if not viz_dir.exists():
            print(f"⚠️  SKIP: Visualization directory not found: {viz_dir}")
            continue
        
        print(f"\n🔄 Processing: {viz_dir.name}")
        
        # Find all edge files recursively
        edge_files_found = list(viz_dir.rglob("*edges*.csv")) + list(viz_dir.rglob("*_viz.csv"))
        
        if not edge_files_found:
            print(f"  ⊘ No edge files found in {viz_dir.name}")
            continue
        
        # Group by pair
        pairs_dict = {}
        for edge_file in edge_files_found:
            # Extract pair name from path
            pair_name = None
            for part in edge_file.parts:
                if "__vs__" in part:
                    pair_name = part
                    break
            
            if not pair_name:
                continue
            
            if pair_name not in pairs_dict:
                pairs_dict[pair_name] = []
            pairs_dict[pair_name].append(edge_file)
        
        # Process each pair
        for pair_name in sorted(pairs_dict.keys()):
            edge_files = pairs_dict[pair_name]
            
            # Process each edge file → regenerate HTML
            for edge_file in edge_files:
                # Determine output HTML file name
                base_name = edge_file.stem.replace("_edges", "").replace("_edges_viz", "").replace("_viz", "")
                html_file = edge_file.parent / f"{base_name}_network_interactive.html"
                
                # Load edges
                edge_df = load_edge_file(edge_file)
                if edge_df.empty:
                    skipped += 1
                    continue
                
                # Regenerate network
                success = regenerate_network_html(
                    pair_name=pair_name,
                    edge_data=edge_df,
                    master_df=master_df,
                    output_file=html_file,
                    physics=args.physics,
                    iterations=args.iterations,
                    seed=args.seed,
                    dry_run=args.dry_run,
                )
                
                if success:
                    if args.dry_run:
                        print(f"  ✓ [DRY-RUN] {pair_name}: {edge_file.name} → {html_file.name}")
                    else:
                        print(f"  ✓ {pair_name}: {edge_file.name} → {html_file.name}")
                    regenerated += 1
                else:
                    skipped += 1
    
    print("\n" + "=" * 80)
    if args.dry_run:
        print(f"✓ DRY-RUN COMPLETE (no files written)")
    else:
        print(f"✓ Regenerated {regenerated} interactive networks")
    if skipped > 0:
        print(f"⊘ Skipped {skipped} due to errors or missing data")
    print("=" * 80)


if __name__ == "__main__":
    main()
